version: '3.4'

networks:
  app-network:
    # external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - app-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_${APP_NAME}
    environment:
      VIRTUAL_HOST: nhatnguyen.online,www.nhatnguyen.online # Thay thế bằng tên miền thực tế của bạn
      LETSENCRYPT_HOST: nhatnguyen.online,nhatnguyen.online
      LETSENCRYPT_EMAIL: nhathdtk@gmail.com # Thay thế bằng email của bạn
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: 'php_${APP_NAME}'
    user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - './:/var/www/html'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
    ports:
      - '9000:9000'
    networks:
      - app-network

  mysql:
    image: 'mysql:5.7.22'
    container_name: 'mysql_${APP_NAME}'
    restart: unless-stopped
    tty: true
    command: --sql_mode=''
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
