name: Deploy to EC2

on:
  push:
    branches:
      - main  # hoặc branch bạn muốn deploy tự động 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh  # Tạo thư mục .ssh nếu chưa tồn tại
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /path/to/your/app  # Thay thế bằng thư mục chứa ứng dụng Laravel trên EC2
            git pull origin main   # Pull code mới từ GitHub
            docker-compose down    # Dừng các container cũ
            docker-compose up -d   # Khởi động lại container với code mới
          EOF
